### ISSUE TITLE
buttons not working

### ISSUE THREAD

**Issue by mohitrathee051** [Zeeshu911/MernStack_Restaurant#1]
![Screenshot 2024-01-06 150718](https://github.com/Zeeshu911/MernStack_Restaurant/assets/115598565/5d9ccfd4-8bf1-498e-a630-cfe93bc01f81)
![Screenshot 2024-01-06 150726](https://github.com/Zeeshu911/MernStack_Restaurant/assets/115598565/491acf5e-719e-4b47-b3a6-8b04ee7a3015)

**Comment by Zeeshu911** [comment]
Hi brother!
I received your both emails. The thing is that I just created a dummy
button but if you want this button to work like other navigation buttons
you can import the Link from react scroll. The below is the code for that
button.

import {Link} from 'react-scroll'

<Link to='menu' smooth={true} duration={500}>Menu</Link>

And for explore menu you can use the same method.

Your feedback is valuable for me I really appreciate it.

Regards,
CodeWithZeeshu!

**Comment by Zeeshu911** [comment]
Awesome, thanks for the update!

**Comment by mohitrathee051** [comment]
can you please merge my pull request so that others do not face the same thing though its a dummy project ..

**Comment by Zeeshu911** [comment]
Yes why not I will do that but I am busy at this moment I'll merge it later.

**Comment by mohitrathee051** [comment]
Please take a moment and do that ...
ps: you are quite good teaching and i will be eagerly waiting for your next project video ..

**Comment by Zeeshu911** [comment]
Thanks brother!
Soon I'll upload another project.

**Comment by Zeeshu911** [comment]
Code updated on github repository. Now you can get the updated version!

Regards,
CodeWithZeeshu
